Fixes for test-forge

diff --git a/test-forge b/test-forge
--- a/test-forge
+++ b/test-forge
@@ -21,10 +21,10 @@ endif
 
 # remove trailing path separators from these input paths
 override TFDIR:=$(TFDIR:%/=%)
-override MF_TESTROOT:=$(MF_TESTROOT:%/=%)
+override TF_TESTROOT:=$(TF_TESTROOT:%/=%)
 
 
-override MFOUT:=$(MF_TESTROOT)/.out
+override MFOUT:=$(TF_TESTROOT)/.out
 override MF_QUIET_BUILDS:=1
 override mf_numprocs:=1
 include $(TFDIR)/_common-forge
@@ -33,84 +33,69 @@ include $(TFDIR)/_common-forge
 .DEFAULT_GOAL:=all
 
 
-define tf_register_test =
-    $(eval override TF_SUB_TOPDEPS+= ${1})
-    $(eval tf_logfile:=$(mf_outdir)/$(mf_target).log)
-endef
-
-
-define _tf_gen_runtarget =
-    _announce_$(mf_target):
-	@printf '%15s :  ' $(mf_target)
-
-    ${1}: _announce_$(mf_target) _build_$(mf_target)
-	@printf 'Running [%-10s]...  ' $(2)
-	@$(TF_ENVVARS) $(mf_program) $(mf_outdir) >$(tf_logfile) 2>&1 || (echo "\033[0;31mFAILED with exit status '$$$$?'\033[0m"; exit 1)
-endef
-
-
-define tf_test_exitstatus =
-    $(call tf_register_test,${1})
-    $(call _tf_gen_runtarget,$(1),exitstatus)
-	@echo "PASS"
-endef
-
-
-define tf_test_sha1sum =
-    $(call tf_register_test,${1})
-    $(call _tf_gen_runtarget,_run_$(1),sha1sum)
-    ${1}: _run_$(mf_target)
-	@TF_SHA1SUM=`sha1sum $(tf_logfile) | awk '{print $$$$1}'` && \
-	 if [ ! "$$$${TF_SHA1SUM}" = "$(2)" ]; then \
-	     echo "\033[0;31mFAILED due to sha1 mismatch" ;\
-	     echo "$(1): sha1 was '$$$${TF_SHA1SUM}', expected '$(2)'.\033[0m" 2>&1 ;\
-	     false ;\
-	 else \
-	     echo "PASS";\
-	     true;\
-	 fi
-endef
-
-
 # INTERNAL: initializes internal state
 define __tf_initialize =
-    $(eval $(call __mf_initialize))
     $(eval override undefine TF_ENVVARS)
+    $(eval override tf_target:=$(1))
 endef
 
 
 # re-initializes, accepts target-name, prepares for target attributes
-define tf_declare_target =
-    $(eval $(call __tf_initialize))
-    $(eval $(call mf_declare_target,$(1)))
-    $(eval override mf_outdir:=$(MFOUT)/$(TF_SUB_SECTION)/$(1))
+define tf_declare_test_target =
+    $(eval $(call __tf_initialize,$(1)))
+    $(eval $(call mf_declare_target,_tf_build_$(tf_target)))
+    $(eval override mf_outdir:=$(MFOUT)/$(TF_SUB_SECTION)/$(tf_target))
+
+    $(tf_target): _run_$(tf_target)
 
     $(mf_outdir):
 	@mkdir -p $(mf_outdir)
 endef
 
 
-define _tf_build_for_test =
-    $(eval $(call tf_declare_target,$(1)))
-    $(eval $(call mf_add_sources,$(tf_testdir),$(2)))
-    $(eval $(call mf_build_executable,$(1)))
+define __tf_register_test =
+    $(eval override TF_SUB_TOPDEPS+=$(1))
+    $(eval tf_logfile:=$(mf_outdir)/$(1).log)
 endef
 
 
-# builds executable from a single source file, and tests via exitstatus
-define tf_build_and_test_exitstatus =
-    $(eval $(call _tf_build_for_test,$(1),$(2)))
-    $(call tf_test_exitstatus,${1})
+define __tf_gen_runtarget =
+    _announce_$(1):
+	@printf '%15s :  ' $(1)
+
+    _run_${1}: _announce_$(1) $(mf_target)
+	@printf 'Running [%-10s]...  ' $(2)
+	@$(TF_ENVVARS) $(mf_program) $(mf_outdir) >$(tf_logfile) 2>&1 || (echo "\033[0;31mFAILED with exit status '$$$$?'\033[0m"; exit 1)
 endef
 
 
-# build executable from a single source file, and tests for sha1sum
-define tf_build_and_test_sha1sum =
-    $(eval $(call _tf_build_for_test,$(1),$(2)))
-    $(call tf_test_sha1sum,$(1),$(3))
+define tf_test_exitstatus =
+    $(eval $(call __tf_register_test,$(1)))
+    $(eval $(call __tf_gen_runtarget,$(1),exitstatus))
+    $(1): _run_$(1)
+	@echo "PASS"
 endef
 
 
+define tf_test_sha1sum =
+    $(eval override _sha1=$(2))
+    $(call __tf_register_test,$(1))
+    $(call __tf_gen_runtarget,$(1),sha1sum)
+    $(1): _run_$(1)
+	@TF_SHA1SUM=`sha1sum $(tf_logfile) | awk '{print $$$$1}'` && \
+	 if [ ! "$$$${TF_SHA1SUM}" = "$(_sha1)" ]; then \
+	     echo "\033[0;31mFAILED due to sha1 mismatch" ;\
+	     echo "$(1): sha1 was '$$$${TF_SHA1SUM}', expected '$(_sha1)'.\033[0m" 2>&1 ;\
+	     false ;\
+	 else \
+	     echo "PASS";\
+	     true;\
+	 fi
+    $(eval override undefine _sha1)
+endef
+
+
+###################################################
 
 
 tf_topdeps:=
@@ -126,9 +111,7 @@ define _tf_include_testdir =
     $(eval override tf_testdir:=$(abspath ${1}))
     $(eval override _tests=$(sort $(wildcard ${1}/[!_]*.mk)))
     $(foreach _test,${_tests},$(call _tf_include,${_test},$(1)))
-    $(eval override undefine _test)
     $(eval override undefine _tests)
-    $(eval override undefine tf_testdir)
 endef
 
 
